### ISSUE TITLE
AI loading picture issue

### ISSUE THREAD

**Issue by dragana1611** [adrianhajdin/project_threejs_ai#44]
<img width="957" alt="aiissue" src="https://github.com/adrianhajdin/project_threejs_ai/assets/77893122/af62634b-543d-4428-aade-cb8daed5102b">

**Comment by prashantkumar76** [comment]
Bro your error is solved or not

**Comment by dragana1611** [comment]
No, it isn't solved. I also generated a new secret key, but it just doesn't work. I didn't even manage to "live" the server. I would be extremely grateful for your help in solving the problem. I also didn't find the code for the save button, and I'm not sure I could do it myself ☺😉https://project-threejs-ai-tailwind.netlify.app/


уто, 12. сеп 2023. у 15:36 prashantkumar76 ***@***.***> је написао/ла:




Bro your error is solved or not

**Comment by dragana1611** [comment]
No, it isn't solved. I also generated a new secret key, but it just doesn't
work. I didn't even manage to "live" the server. I would be extremely
grateful for your help in solving the problem. I also didn't find the code
for the save button, and I'm not sure I could do it myself ☺😉. Tnx in
advanced
Here is the project:
https://project-threejs-ai-tailwind.netlify.app/


уто, 12. сеп 2023. у 15:36 prashantkumar76 ***@***.***> је
написао/ла:

**Comment by celn-pro** [comment]
Here are some things you need to do just get rid of environment self closing tag
```
<ENVIRONMENT preser="city" />
```
After removing that line go ahead and check your server folder to implement the current openAPI method, and if you don't understand just make sure your server files look like these below path
```
https://github.com/celn-pro/full-project-threejs-ai/tree/main/server
```
I hope this resolved, let me know if it did I will be available to help further 🙏

**Comment by dragana1611** [comment]
Tnx a lot ❤, i did everything you said.
I'm making progress 😂, now is:
"Failed to fetch" and I still can't solve the problem 🙆

[image: image.png]

суб, 16. сеп 2023. у 04:29 Ayubu Joseph ***@***.***> је
написао/ла:
